[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
stader_liquid_staking = "SdsLUAYNXCpwdkJ7skmjaF8PxiqoUmNmAQfN2D2Jwmb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/Interviews/stader/fullcode/stader-liquid-staking/.keys/admin.json"

[workspace]
members = ["programs/stader-liquid-staking"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"